tasks:
  - name: App
    init: |
      #  create a default .env file if none present
      if [! -f /tmp/.npm-lock ]; do cp .env.test .env; done
      yarn && \
      gp sync-done install
    command: REACT_APP_PROVIDER=$(gp url 8545) yarn start
  - name: Test
    init: gp sync-await install
    command: yarn test:unit
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8545
    onOpen: ignore
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - juanblanco.solidity
