ci:
  collect:
    staticDistDir: './build'
    assert:
      preset: "lighthouse:recommended"
      assertions:
        first-contentful-paint:
          - "warn"
          -
            "minScore": 0.6