name: pnpm CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2


      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Run lint check
        run: pnpm run lint:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2


      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Generate TypeChain artifacts
        run: pnpm exec typechain --target ethers-v5 --out-dir src/typechain src/abi/*.json

      - name: Run build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2


      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Generate TypeChain artifacts
        run: pnpm exec typechain --target ethers-v5 --out-dir src/typechain src/abi/*.json

      - name: Run test
        run: pnpm run test
